### ISSUE TITLE
Feedback needed :)

### ISSUE THREAD

**Issue by aserafin** [aserafin/grape_logging#21]
Hi, 

I've just merged almost all PR's for the grape_logging and I want to thank you all for your hard work! I will be running master version of gem in my projects during next week to make sure it's stable before pushing to rubygems and it would be really great if you could do the same and post your findings here :)

@diguliu @guizmaii @marshall-lee @987poiuytrewq @yalongzhang @jtmarmon @holstvoogd @scauglog @ayanko @rngtng

**Comment by guizmaii** [comment]
It's in production with the Rails instrumentation at home since a long time ;)

**Comment by aserafin** [comment]
Great - glad to hear :) I did some refactoring though and fixed one bug with appending db times :) Do you think you can try using master?

**Comment by guizmaii** [comment]
I'll look at your commits and will use the master ;)

**Comment by guizmaii** [comment]
Ok for me. 
I don't really know if the `+=` instead of the `=` in the `GrapeLogging::Timings.append_db_runtime` changes something.

I push you a small PR for code lisibility :  #22

**Comment by aserafin** [comment]
It actually does - without it we are only keeping track of last query timing ;)

**Comment by TobiG77** [comment]
master is usable over latest release, good work!

**Comment by guizmaii** [comment]
When do you plan to release the v1.2.0 ?

**Comment by aserafin** [comment]
I will be pushing it today evening

**Comment by rngtng** [comment]
First, thanks for processing the PRs, great job! 
Second, sorry I still havn't found time to look into it in detail. I just ran a quick update and figured it includes breaking changes, e.g. `.formatter` is on `Logger` required. We use https://github.com/TwP/logging where this method is not available. 

But nevertheless, go on with releasing a new version, I'd only bump it up to `2.0.0`  to follow [SemVer](http://semver.org)  correctly. Cheers!

**Comment by aserafin** [comment]
@rngtng it should be pretty easy to make this optional - I will push update today to master and check it with your gem :)

**Comment by rngtng** [comment]
cool thx

**Comment by guizmaii** [comment]
I aslo use https://github.com/TwP/logging.
`.formatter` is required for Logger since v1.1.2 at least. That's why I added the Rails  instrumentation mecanism.
So IMHO, it's not a breaking changes of this version.

If your in a Rails app, the simplest solution is that you use the Rails instrumentation mecanism, see https://github.com/aserafin/grape_logging#logging-via-rails-instrumentation

**Comment by rngtng** [comment]
@guizmaii I saw that section in `README`. But well, we don't use rails....

We're currently on version `1.1.2`. And use it successful with:
```
use GrapeLogging::Middleware::RequestLogger, logger: Logging.logger.root
```

After upgrade to latest branch this fails. When I grep the `1.1.2` code I don't see any mention of `formatter` besides in `README`.

**Comment by aserafin** [comment]
#23

**Comment by aserafin** [comment]
Created new issue for loggers that not expose `.formatter` method #23 - expect fix soon :)

**Comment by guizmaii** [comment]
@rngtng You're right, my bad. Sorry.

**Comment by rngtng** [comment]
tested, looks good thx

**Comment by 987poiuytrewq** [comment]
Thanks @aserafin, @guizmaii and everyone else for getting this merged in - great job! I've been running 876ddf37ff712afd2ab60eba2da88ab6966e8ac1 for the past week in production at 75 requests per minute and it's been working great. :+1:

**Comment by guizmaii** [comment]
Thanks to you @987poiuytrewq ! A lot of the work come from you ! And thanks for the feedback :+1:

**Comment by aserafin** [comment]
Just pusher [1.2.1](https://rubygems.org/gems/grape_logging/versions/1.2.1) to RubyGems! Thanks again for all your hard work and support :clap:

**Comment by rngtng** [comment]
nice thx

**Comment by guizmaii** [comment]
:+1:
