### ISSUE TITLE
Under the concurrent consumption of memory

### ISSUE THREAD

**Issue by tian-xiaobo** [aserafin/grape_logging#3]
Under the concurrent consumption of memory!!!!!

**Comment by aserafin** [comment]
Could you explain little more?

**Comment by ckorhonen** [comment]
If I had to guess I'd imagine @tian-xiaobo may be referring to memory usage when using the gem - we've been experimenting with it recently and saw our unicorn's average memory usage jump by around 100mb with logging enabled.

Nothing fancy, just using the basic configuration as described in the readme.

**Comment by aserafin** [comment]
Even with the latest version?
4 cze 2015 8:59 PM "Chris Korhonen" <notifications@github.com> napisał(a):

**Comment by marshall-lee** [comment]
@ckorhonen @aserafin i think it's #7 related!

**Comment by aserafin** [comment]
@ckorhonen @tian-xiaobo @marshall-lee fixed thanks to @marshall-lee PR and released to rubygems https://rubygems.org/gems/grape_logging/versions/1.1.1
