### ISSUE TITLE
Logging to file and not STDOUT

### ISSUE THREAD

**Issue by BenJaziaSadok** [aserafin/grape_logging#41]
Hello, i used the logging to a file option and it works well.
I'm trying to remove logging to STDOUT and keep only logging to an external file.
Is that possible?

**Comment by aserafin** [comment]
It should be possible but it's more a feature of the logger you're using (for example Rails logger etc.) then this gem itself. Could you give some more details about that?

**Comment by BenJaziaSadok** [comment]
I use a log analytic service (ELK) and i send to it the rails main log and the api log file.
Each log type should be on a separate file so the parsing tool would work on each log line. (I use two types of parse).
So in order to make this clean (no api log redundancy) i thought of removing the log lines from the main log file.
