### ISSUE TITLE
Rails 6.0.0.rc1 deprecation warning: ActionDispatch::Http::ParameterFilter

### ISSUE THREAD

**Issue by svenmalkus** [aserafin/grape_logging#61]
ParameterFilter inherits from ActionDispatch::Http::ParameterFilter which will be removed from Rails 6.1:

`DEPRECATION WARNING: ActionDispatch::Http::ParameterFilter is deprecated and will be removed from Rails 6.1. Use ActiveSupport::ParameterFilter instead.`

**Comment by windy** [comment]
+1 

The same problem

**Comment by aserafin** [comment]
this was fixed with #63 and just published to rubygems 👍
