### ISSUE TITLE
ActiveSupport::ParameterFilter depends on Rails > 6.0

### ISSUE THREAD

**Issue by CodingAnarchy** [aserafin/grape_logging#64]
The most recent release of `grape_logging` depends on `ActiveSupport::ParameterFilter`, which is only compatible with Rails 6.

This broke my Rails 5.2 application upon upgrading.  Please update the gemspec to prevent updating past 1.8.1 for Rails 5.2 or modify the code to handle both Rails versions.

**Comment by mikenichols** [comment]
Just ran into this today. We're on rails 5.1.4 and bumping grape_logging to 1.8.2 breaks our app.

**Comment by exosty** [comment]
Same for me

**Comment by aserafin** [comment]
@CodingAnarchy @mikenichols @exosty I've pushed a fix to master but I don't have any app handy to test this. Could you please check and report back?

**Comment by mikenichols** [comment]
I pulled down the latest 1.8.2 and the problem seems to be resolved. Thanks for taking care of this.

**Comment by ranjithnalimela** [comment]
@aserafin Could you please create a **tag**(1.8.3) with latest changes you made on the **master** branch.

**Comment by aserafin** [comment]
Tagged and pushed to rubygems - thanks you all and @mikenichols especially for the testing 👍
